### ISSUE TITLE
While migrating threat model from Microsoft template to Threats Manager Studio it becomes very complex

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#18]
This is the rule definition from microsoft template  .  I am able to understand it

```
<GenerationFilters>
        <Include>(target is 'SE.P.TMCore.WebApp'  or target is 'SE.P.TMCore.WCF' or target is 'SE.AS.TMCore.WebAPI' or target is 'SE.AA.TMCore.APIApp' or target is 'SE.AS.TMCore.AppService' or target is 'SE.AS.TMCore.CloudServices' )</Include>
        <Exclude>
        </Exclude>
      </GenerationFilters>
      <Id>TH96</Id>
      <ShortTitle>An adversary can gain access to sensitive data by performing SQL injection through Web App / API/ API-App or WCF Service </ShortTitle>
```
The migrated rule from threat manger studio is much bigger
![Part1](https://user-images.githubusercontent.com/31912418/146937553-e150f5db-6e41-46b2-b78a-870081a1ba9c.PNG)
![Part2](https://user-images.githubusercontent.com/31912418/146937567-c7ccf947-eb65-42b4-8696-61e7bb6b79bb.PNG)

I am able to understand Part1 but not able to understand why Part2 is there.  Can you help  me understand on how threat manager studio rule has been migrated .  FYI this rule is working but wanted to understand the internals to troubleshoot some migrated rules.   For me the threat is getting generated but when I click on the test button  I am not able to see the result.
When do we use object properties in formulas ?

**Comment by simonec73** [comment]
I agree. The result doesn't seem right. Can you provide me with a repro, please? Thanks.

**Comment by rsrinivasanhome** [comment]
I checked again .  In normal scenario this does not come.  I think the issue occurs when you apply templates which has some similar threat types .  I am trying to resimulate.

**Comment by simonec73** [comment]
Threat Types going by the same name? Yes, I can see that it could make import problematic. But, why would you have that?

**Comment by rsrinivasanhome** [comment]
I am trying to create a  common threat manager studio template to be used in two scenarios

- When I am creating a new threat model
- When I migrate an existing threat model from Microsoft template which is derived from a base microsoft template say "A"

My threat manager studio template is based on my existing microsoft base template "A"
+ Some corrections for the auto gen rules to work with threat manger studio

Now If migrate an existing microsoft threat model and apply my threat manager studio template using import template option.  There are bound to be the overlapping threats types.  
I think this will make import problematic.  Will the import process overwrite all the common threat types with the imported one ?
 Should the merge template option be used instead ?

**Comment by simonec73** [comment]
If you have two Threat Types with distinct IDs going by the same name in two different templates, when you import the first and then the second template:
- A single Threat Type is created, with all the properties of the one found in the first template.
- The creation rules are merged.
The same goes for the Mitigations.

If you want a different behavior, that is the creation of two distinct Threat Types and two distinct Mitigations, then you have to use the Merge function. In this case the IDs win.

So, you have both options. You decide what you prefer to do.

**Comment by rsrinivasanhome** [comment]
In my case the IDs will be same.  Suppose I have a threat manager studio template say - A  with some fixes on some of the threat types.
I have created a new threat model say - B.   In B  I add a new threat type.   I click on import template . 
B will get all the threat types available in A.  (Basically A is the master for threat types).  The newly added threat type in B will be missing.  Will this be the behaviour ? 
Do we have a way to version the template applied ?  By opening threat Model B how do I know Threat template A has been applied ?

**Comment by simonec73** [comment]
Importing a template does not remove the existing Threat Types or Mitigations. It is incremental. This choice supports the model where you have multiple templates specialized on a specific subset of the available systems (like one for Azure IaaS Core, one for Azure PaaS Core, one for Azure PaaS Containers, etc.). The idea is to define the same Threat Types in all templates and that by importing a selection of the available templates, you get a knowledge base designed to cover all the technologies you need.
So no, the Threat Type you have only in B would not be removed by importing A.

Regarding the second point, which is the possibility to store references to the templates of origin, I confirm that I have already had a similar request. This feature is already in the backlog, but I am not planning to implement it in any upcoming releases. But do not despair because it may still eventually happen.

**Comment by rsrinivasanhome** [comment]
My idea is that I will have one template will all fixes inside.  When any threat model uses the import template option all fixes made in the template need to be applied to the threat model.   Will this happen ?

**Comment by simonec73** [comment]
Not with templates. Check with the Merge function. It should work, depending on the type of the fixes. If not, please let me know and I will troubleshoot it.

For the records, if you have a specific list of fixes you want to apply, it may be easier to write an Extension. An example is in https://github.com/simonec73/threatsmanager/Samples/SampleExtensions. By writing a simple Action, you would be able to revise automatically not only the Threat Types and Mitigations, but also the imported Threat Events, if necessary.
It requires some C# skills.

**Comment by rsrinivasanhome** [comment]
Can the threat model be exported to a text file ?  This would help in manually checking if a particular threat model has the latest template applied

**Comment by simonec73** [comment]
Yes, save it as a TMJ file. It creates a JSON file.
Or you can change the extension of the TM file to ZIP and then open it and extract the threatmodel.json file. It has the same content of the TMJ file.

**Comment by rsrinivasanhome** [comment]
Thanks this information is very helpful.

**Comment by rsrinivasanhome** [comment]
Based on using the merge and import template feature this is my understanding

- If you have not applied any template on your threat model use import template
- If you have already applied a template on your threat model use the merge feature.

**Comment by simonec73** [comment]
No, this is not correct. Import template is the way to go. 

You need to use the Merge only because you are using the same name for different threats, which should not happen. Please ensure that different threats have the same name and ID.
Merge is a workaround to cover for your situation, but it is not the recommended approach.
