### ISSUE TITLE
Microsoft Threat model - way to show {source.Name} in threat event

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Microsoft threat model supports the following syntax
`   <ShortTitle> An adversary may spoof {source.Name} with a fake one</ShortTitle>  `
and threat event shows the source name

**Describe alternatives you've considered**
Is there any work around for this type of feature ?

**Additional context**

**Comment by simonec73** [comment]
Name placeholders are not supported. You have to change the name of the Threat Type after migration.
