### ISSUE TITLE
Apply Schema Additional properties not reflecting uniformly in Item template

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#21]
**Describe the bug**
To make things clear I am not sure if this is a bug or I am doing something wrong.   I do not see all the manually added properties to my item template.  

**To Reproduce**
1. I have added some properties to one of my items templates - ios App.  I then clicked on apply schema.   View screen shot below
![image](https://user-images.githubusercontent.com/31912418/147923622-f5032d63-58dc-4cb4-b6ff-4c1a316975c9.png)

2. I had previously dragged the item template- ios App on my diagram and I am able to see the additional properties

![Extra Properties Visible](https://user-images.githubusercontent.com/31912418/147923790-644641a6-f38d-473f-93cb-aafcb3d09f0f.PNG)

3. Now I create a new instance of the ios app.  It is missing the newly added properties
![Secondiosappnotvisible](https://user-images.githubusercontent.com/31912418/147923876-057460e9-d769-4235-917a-36708484cb27.PNG)

**Expected behavior**
The newly added properties should be visible when even I am using the ios app in my threat model.  Now I see it the first time only.

**Screenshots**
If applicable, add 

screenshots to help explain your problem.

**Additional context**

**Comment by simonec73** [comment]
The behavior is by design. Please note that the iOS App property schema is applied to Processes, while the iOS App you created last is an External Interactor. I guess that the problem is that you have more iOS Apps going by the same name. You may need to change the name in the original template, for example renaming the External Interactor one to "[External] iOS App".

By the way, I've double checked, creating a file from scratch, and I confirm it works.

**Comment by rsrinivasanhome** [comment]
You analysis is correct .  I fell back to a previous version which I had corrected using the microsoft threat modeling template and now after I import the template and I do  not face this issue any more.  

I tried merging my previous work on threats manager studio onto the fresh template I have now created from the corrected microsoft template .  Some of my observations
1) When I try to to merge on a .tm file  I do not see an action or differences popping up .  Does this merge immediately ?
2) When I import the mitigations alone then link between the threat event is cut

I need to selectively move some Rule (alone) corrections from one threat manager studio file to my new template.  What is the advised approach to do this ?
