### ISSUE TITLE
Importing user defined threat fails , "OR" is not recognized when importing an mstmt threat model

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#35]
**Describe the bug**
Import bug 1 - >  User defined threat make import fail
Create a user defined threat in mstmt
Try importing the threat model in Threats manger studio it fails

Import bug 2 - >  "OR" statement in function are ignore and rest of formula is cut.  This works fine for "or"

**To Reproduce**
Bug 1
1. Go to 'TestUserDefined.tm7'
2. Import the threat model
3. Import failure '
5. 
![image](https://user-images.githubusercontent.com/31912418/195770747-dd3c30bc-2221-467f-a206-c1527edd64cc.png)

Bug2 
1) import the threat model  template - azureteamplate_simulate..
2) view the threat type " An adversary can gain access to sensitive PII or HBI data in Target|
3) Formula is missing the comparison post "OR"
![image](https://user-images.githubusercontent.com/31912418/195770539-675706ca-3edb-448e-8c28-13cac01a738d.png)

**Expected behavior**
Error to remove user defined threat or ability to import user defined threat.
**Screenshots**

**Additional context**
[TestUserDefined.tm7.txt](https://github.com/simonec73/threatsmanager/files/9782758/TestUserDefined.tm7.txt)
[Uploading AzureTemplate_simulatedSample.tb7.txt…]()

**Comment by simonec73** [comment]
Thank you. Issues added to the backlog for fixing.

**Comment by simonec73** [comment]
Hi @rsrinivasanhome , I'm addressing the bugs. The first one should be ok, but for the second I need you to reupload the file. The problem is that I cannot download it. Thanks!

**Comment by rsrinivasanhome** [comment]
Not sure what went wrong in my last upload .  This time I am uploading a zip file.
[AzureTemplate_simulatedSample.tb7.zip](https://github.com/simonec73/threatsmanager/files/9865949/AzureTemplate_simulatedSample.tb7.zip)

Download the file
unzip
Remove the the .txt extension
import

**Comment by simonec73** [comment]
Both issues have been fixed. I'm working on other fixes, then I will package and upload a new version of the TMT Import Extension Library.

**Comment by simonec73** [comment]
A new version of the TMT Import extension library is out. It fixes the issue. Thank you for your patience.
