### ISSUE TITLE
Silent Crash of application when we try to open a corrupt threatmodel diagram

### ISSUE THREAD

**Issue by kalyancheerla** [simonec73/threatsmanager#48]
**Bug Report**
A silent crash of threats manager studio windows application when we try to open a corrupt threat model diagram i.e., when the parentID and ID of any entity or group is same. The application silently closes down leaving the .tmlock file when we press on diagram 1 to open.

**To Reproduce**
1. Open the buggy.tm with TMS windows app.
2. Once the document is successfully loaded, press on the diagram 1.
3. App crashes silently
4. .tmlock file is left behind without cleanup and the it doesn't report any error.

**Expected behavior**
Expecting the app at the very least to clean the tmlock file or report error and doesn't open the diagram for the corrupt threat model.

**Screenshots**
ID and parentID were same,

![2023-04-13 11_27_36-bug](https://user-images.githubusercontent.com/32354220/231831711-1801b1d5-3cc0-48be-982a-11c9e0a008da.png)

Below zip file contains the buggy.tm TMS file,
[reqfiles_for_bug.zip](https://github.com/simonec73/threatsmanager/files/11224590/bug.zip)

**Additional context**
![image](https://user-images.githubusercontent.com/32354220/231832237-b44ae27b-ab86-47be-9896-c84b91c339fb.png)

**Comment by simonec73** [comment]
Thank you for the nice verification. I will fix this.

**Comment by kalyancheerla** [comment]
I am happy to help, if you could provide me with your thoughts on its implementation. Also, it would lessen your work and provide me with some open-source credits that I can boost-off about! 😄
