### ISSUE TITLE
Feature request: Non-administrator installation

### ISSUE THREAD

**Issue by s4parke** [simonec73/threatsmanager#51]
This looks like a really interesting tool and I am certainly going to download it and try the examples. Thanks very much for all the great work and documentation!

I wonder if it would be possible to deploy a version of the installer or the program executable that does not require elevated (Admin) privileges. That would make it more accessible to users who have security restrictions or otherwise skeptical of granting elevated privileges.

I'll download the source and build it locally to try to answer my own question. Thanks again.

**Comment by simonec73** [comment]
Thank you. I can confirm that I plan to create a "Portable" version of TMS. It will include the most common extensions (AutoThreatGen + Quality) and will require no installation. You will be able to execute it as a normal, unprivileged user, from any folder, even from a USB drive.
You will not be able to access the online help, but most of the other capabilities will be available.
You will be able to download the "Portable" TMS as a ZIP file.
