### ISSUE TITLE
Immediate Redrawing when threatmodel was imported

### ISSUE THREAD

**Issue by kalyancheerla** [simonec73/threatsmanager#52]
Feature Request:
This could be a feature request instead of a straightforward bug. The TMS application does not redraws immediately when an extension imports the ThreatModel and would love if it does that instead of saving the threatmodel and reopening it again.

    Install the MicroSvcsThreatsMapper.msi extension.
    Check if the extension is available in the TMS app.
    Click on it and import the microsvcs.json dump in the below reproduce.zip file.
    After import was successful the TMS app doesn't show the diagrams in the Home section immediately.
    Check the below video for more clarity.

Video:

https://github.com/simonec73/threatsmanager/assets/32354220/914e514c-aae1-436a-9c71-2d218b2675d2

Expected behavior:
Expecting the TMS app to load the threat model immediately instead of saving the threatmodel and reopening it.

Files:
[reproduce.zip](https://github.com/simonec73/threatsmanager/files/11593843/reproduce.zip)

Note:
Disable both the validation checks namely, assembly must start with one of the prefixes and assembly must be signed with one of the certificates.

**Comment by simonec73** [comment]
You should simply raise event RefreshPanels like follows, from the IMainRibbonExtension: `RefreshPanels?.Invoke(this);`.

**Comment by simonec73** [comment]
Ok, I checked and double-checked. Apparently, my previous answer was correct. If you call RefreshPanels from your IMainRibbonExtension as `RefreshPanels?.Invoke(this)`, you trigger the refresh of all panel lists, including the list of Diagrams. This currently adds the diagrams to the list; it does not reorder them. I'm trying to fix the ordering issue with the next version. But I can confirm that raising the said event works. Therefore, I close the issue.
