### ISSUE TITLE
threat model get cluttered on opening 

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#53]
**Describe the bug**
I am able to create a diagram of my threat mode it look fine l .  However when I try opening it becomes  very cluttered and unreadable.
Is there any setting I am missing ?

**Comment by simonec73** [comment]
That's a known bug triggered by the adoption of different DPIs monitors. I will fix this with the next version. Thank you for noticing it.

**Comment by rsrinivasanhome** [comment]
Is there any work around for this issue ?  Will keeping the number of components in threat model low help ?  Any guideline  to reduce occurrence of this issue ?

**Comment by simonec73** [comment]
Yes, there is. 

1. Save the file as JSON (TMJ). 
2. Open it with an editor (for example, VS CODE).
3. Go to the Diagrams node and then open the Properties of the first diagram. You will see there a property that is of type PropertyDecimal. The value corresponds to the original HiDPI scale. If the diagram looks too small, the value may be too big: make it smaller to adjust. If, instead, the diagram seems too big, then reduce the value.
4. Repeat point 3 for every diagram in the threat model.

If you know the DPI scale adopted on the computer that created the diagrams, that would be the correct value to use.

I hope it helps.

**Comment by rsrinivasanhome** [comment]
I am facing this issue recently.  I think previously i was using only my laptop .  Will be be updating the threat model sometimes with extended monitor cause this issue.  Is there any resolution which will reduce the number of times this issue occurs.

**Comment by simonec73** [comment]
Not for now, no. I'm working on version 2.0, which revamps diagrams and addresses this issue, but for now there is nothing else to do.

**Comment by simonec73** [comment]
I would not go that route. It's easier to use the process I proposed above.

**Comment by rsrinivasanhome** [comment]
For this point 3 `"Go to the Diagrams node and then open the Properties of the first diagram. You will see there a property that is of type PropertyDecimal. The value corresponds to the original HiDPI scale. If the diagram looks too small, the value may be too big: make it smaller to adjust. Instead, if the diagram seems too big, then reduce the value."`

Can you copy the tags ?  It will make it easier for me to follow

**Comment by rsrinivasanhome** [comment]
It does help to some extent .  I have created a multi diagram threat model .  What I see is that the boundary sizes some time increase and distort the diagram. not sure of the reason.
If I use the boundary in two diagrams will it effect the size.

**Comment by rsrinivasanhome** [comment]
After playing a little longer understood your approach is the best.

**Comment by simonec73** [comment]
> It does help to some extent . I have created a multi diagram threat model . What I see is that the boundary sizes some time increase and distort the diagram. not sure of the reason. If I use the same boundary in two diagrams will it effect the size. ?

Trust boundary location and size is defined per diagram. Therefore, no what you set for one does not affect the other.

**Comment by simonec73** [comment]
> After playing a little longer understood your approach is the best.

Glad to hear. I'm actively working on the next version. It will address the issues you are facing in multiple ways, including executing the remediation activities without requiring that workaround.

**Comment by rsrinivasanhome** [comment]
Thank you very much .  Keep us informed when the next version will be available .
