### ISSUE TITLE
Threats manager Studio 2.1.0.0 - Export Word not working

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#56]
**Describe the bug**
Export to word feature is not working on 2.1.0.0 .   I think a new version of the plugin is required
On the old version this feature is working fine.
![versions](https://github.com/simonec73/threatsmanager/assets/31912418/6a788e64-21dd-4f74-8ddb-186d0a9b7a27)

1. Go to '[...](https://threatsmanager.com/downloads/)'   https://downloads.threatsmanager.com/latest/TMPlatform_ReportingAddIn.msi
2. Download the plugin
3. With the template Azure PaaS Core.docx tried to export  to word by clicking on generate document option

![image](https://github.com/simonec73/threatsmanager/assets/31912418/87a77f5d-1398-4fe7-8df8-c7f56ca6d7da)

**Comment by simonec73** [comment]
Yes, it is a known bug, solved with v2.1.1. I will publish it in a few hours. You will see the new installation artifacts on Monday.
