### ISSUE TITLE
"Auto Gen Rules" button is missing from Threats Manager Studio

### ISSUE THREAD

**Issue by lberan2021** [simonec73/threatsmanager#6]
I found the same issue had been posted at https://threatsmanager.com/troubleshooting/auto-threat-generation/
But the site suggestion did not resolve my issue.  

![TMS screenshot](https://user-images.githubusercontent.com/81331988/112389693-8b678880-8ccb-11eb-975f-4d610f342b73.png)

**Comment by simonec73** [comment]
That's not a bug. You have to install also the Auto Threat Gen extension library from https://threatsmanager.com/download.
