### ISSUE TITLE
Review Notes feature and Annotation notes feature not opening in very few migrated threat models

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#60]
**Describe the bug**
We have noticed on very few migrated threat models  (created on old versions of threats manager studio and opened in version 2.1.1)

**To Reproduce**
1. Open existing threat model (saved on old version of threats manager studio before) 
2. Click on 'Review Notes'  does not open a new window .  Existing screen is displayed
3. Click on 'Quality Dashboard' it works
4. Click on Annotation Notes does not open a new window .  Existing screen is displayed

**Expected behavior**
"Review Notes and Annotation notes are visible

Can we collect any troubleshooting information ?  We do not see any exceptions or error logs ?  We are not able to see this issue in other threat models .

**Comment by simonec73** [comment]
I've found a bug with the Annotations introduced with v2.1.0. It has been solved with v2.1.3. I'm publishing the new version today.
