### ISSUE TITLE
Duplicate definition for Threats Property Schema

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#64]
High level issue -
I have created a threats manager studio template and have 2 versions (lower, higher) of the template defined. 
I first create a template using the lower version of the template and saved the threat model. (I have customized the structure of Threats to add a custom field in the template)
I then open the threat model and apply the second version of the template and save the threat model.
When I open the property schema I see a duplicate definition of threats 

![image](https://github.com/simonec73/threatsmanager/assets/31912418/321d19e4-2165-4fd8-b8cb-bef83b9ad56d)

Detailed steps to reproduce the issue 

1.Create a new threat model
2.Click import knowledge Base and import 
[v1template.tmt.txt](https://github.com/simonec73/threatsmanager/files/14237994/v1template.tmt.txt).
3. Create a diagram  .  Close the the threat model
4. Reopen the threat mode again apply 
[v2template.tmt.txt](https://github.com/simonec73/threatsmanager/files/14237995/v2template.tmt.txt) by using import merge - all options .

sample threat model provided -  [TryAgain2.tm.txt](https://github.com/simonec73/threatsmanager/files/14237993/TryAgain2.tm.txt)

**Expected behavior**
property schema should have only one definition of threat.

For now I am deleting the newly added -"Threats"  schema (via property schema screen)  it appears to work so far .  Let me know if I will face any issues. Looks like workaround is available for this issue.

**Comment by simonec73** [comment]
Addressed with v2.1.4.

**Comment by rsrinivasanhome** [comment]
using version 2.1.4.0  the old workaround  still works for the newly created threats

**Comment by rsrinivasanhome** [comment]
The work around is not working when we regenerate threats the duplicates are created again .
