### ISSUE TITLE
Formulas assigned to mitigations  not exported /imported via knowledge base

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#65]
**Describe the bug**
Mitigations where formula's are used can not be exported to a new threat model by the export knowledge base template and import knowledge base  feature

**To Reproduce**
1. create a threat model and define a threat type . Assign a mitigation and assign a formula  to the threat type 
[CreateTemplatewtihmitigationformula.tm.txt](https://github.com/simonec73/threatsmanager/files/14385382/CreateTemplatewtihmitigationformula.tm.txt)

2. Click on 'export knowledge base'  get template like 
[withmitigationformula.tmt.txt](https://github.com/simonec73/threatsmanager/files/14385396/withmitigationformula.tmt.txt)

3. Create a new threat model and click on import knowledge base
4. Rules associated to mitigations are missing.

**Comment by simonec73** [comment]
Solved in v2.1.4.

**Comment by rsrinivasanhome** [comment]
Verified on v2.1.4  -  The tickets is closed .  Thank you

**Comment by rsrinivasanhome** [comment]
Re export of the template is required
