### ISSUE TITLE
Boundaries are not imported while using importing via Merge Template and Threat Model Option

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#66]
1. Create a template with 1 boundary sample
[BoundaryTemplate.tmt.txt](https://github.com/simonec73/threatsmanager/files/14414032/BoundaryTemplate.tmt.txt)

2. Create a new threat model .  Import template using merge threat models and template method option
3. Boundary present in the template is not visible in the new threat model

**Comment by simonec73** [comment]
Fixed with v2.1.4.

**Comment by rsrinivasanhome** [comment]
Verified fixed with V.2.1.4
