### ISSUE TITLE
Post importing template unable to view AutoGen Rules or threat types

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#67]
**Describe the bug**
I have created a template .  I have imported the template.  When I view the threat types or auto gen rules I am not able to see the screen popup. No exception occurs.  If I try to export the knowledge base i get an error on 26-Feb -2024. Hope telemetry would have been shared.

**To Reproduce**
1. Go to Import template
2. Click on Threat types or Auto Gen rules no response.  If I had previously open auto gen rules and click import I see the rules with create rule button. but rule displays
3. No exception occurs
4. I click on export knowledge base  .  Below exception occurs
![image](https://github.com/simonec73/threatsmanager/assets/31912418/7a670534-d39d-4324-9254-1777717d19ab)

5. With 26 - Feb-2024 telemetry can this issue be sorted out.

**Comment by rsrinivasanhome** [comment]
@simonec73  is there any place I can see the exception

**Comment by simonec73** [comment]
Thank you. I think I can see the error. I am working on it.
Related to your question, I'm sorry but I cannot provide you access to the traces.

**Comment by simonec73** [comment]
Please check if the problem occurs with v2.1.4, and then eventually close the case.

**Comment by rsrinivasanhome** [comment]
Problem no longer occurs.  Version  v 2.1.4 closes the issue.  Thanks .
