### ISSUE TITLE
Threats Manager Studio - Merge Option

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#80]
**Describe the bug**
I have built a threat model using a lower version of my threat template.  I tried to upgrade to a new version by using the merge option  (Import Threat Model and Knowledge Options)

1. When I click to merge updated requirements I am getting the below error
2. 
![image](https://github.com/user-attachments/assets/50f6e3c5-cff8-4e6f-867e-fe83ce18f5a3)

3. On the server do you see any error log for this issue ?
4. Is there any other way to update a revised threat model template to my threat model ?

**Comment by simonec73** [comment]
Unfortunately, I cannot replicate and the information I have available is not enough to determine the root cause. Can you please check with the new version, and then eventually reopen this bug?
