### ISSUE TITLE
Annotation not working

### ISSUE THREAD

**Issue by satyajitlulu** [simonec73/threatsmanager#81]
**Describe the bug**
Annotation  and create a new review note not working
**To Reproduce**
I import a MS Threat model file, when i am trying to add review note or use annotation enable, nothing seems working.

The version of Threat manager studio : 2.2.4

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SoldierFace** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by satyajitlulu** [comment]
I tried to download but my antivirus is reporting it as virus so not able to download
