### ISSUE TITLE
Merge Threat model is showing element which have not changed

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#87]
**Describe the bug**
I generally perform the following activities

1) Create a threat model template
2) Create threat model using the template.
3) Update the template 
4) Reapply the template on the threat model using the merge threat model or knowledge base option
5) The merge template does not show correct differences so I have to remember the changes and make sure they are selected. Not sure if there is a better feature to be used in this scenario

**To Reproduce**

[Threat Model Based On Template.tm.txt](https://github.com/user-attachments/files/17520568/Threat.Model.Based.On.Template.tm.txt) is  threat model created based  on
[MyFirstTemplate.tmt.txt](https://github.com/user-attachments/files/17520567/MyFirstTemplate.tmt.txt)

1. Go to '
[Threat Model Based On Template.tm.txt](https://github.com/user-attachments/files/17520568/Threat.Model.Based.On.Template.tm.txt)

2.Click  on Merge Threat model and select 
[MyFirstTemplate.tmt.txt](https://github.com/user-attachments/files/17520567/MyFirstTemplate.tmt.txt)
As visible in screen shot. No difference exist .
![Issue](https://github.com/user-attachments/assets/7affa70e-f14b-410a-a5d1-8c7f9f0cac1d)

3. But Merge shows differences which are not present.

**Comment by simonec73** [comment]
I confirm the issue. This is caused by the wrong generation of the property in the imported system. I'm fixing it with the upcoming version.
