### ISSUE TITLE
Cannot see Import CAPEC Threats feature

### ISSUE THREAD

**Issue by antoniachen** [simonec73/threatsmanager#9]
Hi Simone,

I was following along with your YouTube video and you mentioned a way to import CAPEC threats. I downloaded version 1.4.2.0, but i do not see that option..

![image](https://user-images.githubusercontent.com/42491413/122140158-1bf1d700-ce7d-11eb-866d-f8a908278785.png)

I've download all the available extensions but it still doesn't show up. is there any other settings i need to change?

Thanks!!

**Comment by simonec73** [comment]
Thank you, @antoniachen 
Yes, I confirm that this feature is still present. To see it, you need to configure TMS in Pioneer Execution Mode. Please refer to https://threatsmanager.com/training/intro/start-here/execution-mode/ for more information.

Next version (1.5.0) will replace this feature with a much more powerful one, which will provide a graph composed of the nodes described in MITRE CWE, CAPEC and ATT&CK, and possibly even more.

Thank you!
